export const dummy_data = [
  {
    _id: "1",
    name: "House",
    description: "House for Family Vocation",
    rent: true,
    sell: false,
    price: 9999.99,
    rooms: 2,
    rating: 4.5,
  },
  {
    _id: "2",
    name: "Appartement",
    description: "House for Family Vocation",
    rent: true,
    sell: false,
    price: 9999.99,
    rooms: 1,
    bedroom: 1,
    rating: 4.5,
  },
  {
    _id: "3",
    name: "House",
    description: "House for Family Vocation",
    rent: true,
    sell: false,
    price: 9999.99,
    rooms: 3,
    rating: 4.5,
  },
];
